<a href="https://colab.research.google.com/github/DevikaSanthosh24/Employee-Attrition/blob/main/1_Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Required Libraries

In [ ]:
import pandas as pd
import numpy as np

Upload the Dataset

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving employee_attrition_dataset_10000.csv to employee_attrition_dataset_10000.csv

Load Dataset from Google Drive

In [ ]:
import pandas as pd
df = pd.read_csv("employee_attrition_dataset_10000.csv")

Display First Five Rows

In [ ]:
df.head()

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,1,58,Male,Single,Finance,Manager,5,7332,81,24,...,No,9,48,16,4,1,1,49,3,No
1,2,48,Female,Divorced,HR,Assistant,4,6069,55,18,...,Yes,9,57,10,4,1,1,25,1,No
2,3,34,Female,Married,Marketing,Manager,4,11485,65,6,...,Yes,3,55,1,1,4,3,21,1,Yes
3,4,27,Female,Divorced,HR,Manager,4,18707,28,12,...,No,9,53,2,3,4,1,46,2,No
4,5,40,Male,Married,HR,Analyst,1,16398,92,3,...,No,1,54,11,1,1,1,43,4,No

Check Dataset Shape

In [ ]:
print(df.shape)

(10000, 26)

Dataset Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Employee_ID                    10000 non-null  int64
 1   Age                            10000 non-null  int64
 2   Gender                         10000 non-null  object
 3   Marital_Status                 10000 non-null  object
 4   Department                     10000 non-null  object
 5   Job_Role                       10000 non-null  object
 6   Job_Level                      10000 non-null  int64
 7   Monthly_Income                 10000 non-null  int64
 8   Hourly_Rate                    10000 non-null  int64
 9   Years_at_Company               10000 non-null  int64
 10  Years_in_Current_Role          10000 non-null  int64
 11  Years_Since_Last_Promotion     10000 non-null  int64
 12  Work_Life_Balance              10000 non-null  int64
 13  Job_Satisfaction               10000 non-null  int64
 14  Performance_Rating             10000 non-null  int64
 15  Training_Hours_Last_Year       10000 non-null  int64
 16  Overtime                       10000 non-null  object
 17  Project_Count                  10000 non-null  int64
 18  Average_Hours_Worked_Per_Week  10000 non-null  int64
 19  Absenteeism                    10000 non-null  int64
 20  Work_Environment_Satisfaction  10000 non-null  int64
 21  Relationship_with_Manager      10000 non-null  int64
 22  Job_Involvement                10000 non-null  int64
 23  Distance_From_Home             10000 non-null  int64
 24  Number_of_Companies_Worked     10000 non-null  int64
 25  Attrition                      10000 non-null  object
dtypes: int64(20), object(6)
memory usage: 2.0+ MB

Check Data Types

In [ ]:
df.dtypes

Employee_ID                       int64
Age                               int64
Gender                           object
Marital_Status                   object
Department                       object
Job_Role                         object
Job_Level                         int64
Monthly_Income                    int64
Hourly_Rate                       int64
Years_at_Company                  int64
Years_in_Current_Role             int64
Years_Since_Last_Promotion        int64
Work_Life_Balance                 int64
Job_Satisfaction                  int64
Performance_Rating                int64
Training_Hours_Last_Year          int64
Overtime                         object
Project_Count                     int64
Average_Hours_Worked_Per_Week     int64
Absenteeism                       int64
Work_Environment_Satisfaction     int64
Relationship_with_Manager         int64
Job_Involvement                   int64
Distance_From_Home                int64
Number_of_Companies_Worked        int64
Attrition                        object
dtype: object

Check Missing Values

In [ ]:
df.isnull().sum()

Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

Check Duplicate Rows

In [ ]:
print(df.duplicated().sum())

0

Verify Missing Values

In [ ]:
df.isnull().sum()

Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

Check Unique Values

In [ ]:
for column in df.select_dtypes(include='object'):
    print(column)
    print(df[column].unique())
    print()

Gender
['Male' 'Female']

Marital_Status
['Single' 'Divorced' 'Married']

Department
['Finance' 'HR' 'Marketing' 'Sales' 'IT']

Job_Role
['Manager' 'Assistant' 'Analyst' 'Executive']

Overtime
['No' 'Yes']

Attrition
['No' 'Yes']

Standardize Text Values

In [ ]:
for column in df.select_dtypes(include='object'):
    df[column] = df[column].str.strip().str.title()

Statistical Summary

In [ ]:
df.describe()

,Employee_ID,Age,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,Years_in_Current_Role,Years_Since_Last_Promotion,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Training_Hours_Last_Year,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,39.561800,2.990800,11436.716700,57.032300,14.936200,7.451300,4.471900,2.502400,3.038000,2.507700,49.588900,4.984400,44.473500,9.410200,2.493100,2.491400,2.505400,25.272000,2.516600
std,2886.89568,11.454986,1.410643,4926.528302,24.703261,8.431657,4.042903,2.891617,1.112348,1.414764,1.120833,28.801393,2.580043,8.611662,5.760335,1.120927,1.115101,1.116018,14.219474,1.113934
min,1.00000,20.000000,1.000000,3000.000000,15.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,30.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2500.75000,30.000000,2.000000,7182.500000,36.000000,8.000000,4.000000,2.000000,2.000000,2.000000,2.000000,25.000000,3.000000,37.000000,4.000000,1.000000,1.000000,2.000000,13.000000,2.000000
50%,5000.50000,40.000000,3.000000,11401.500000,57.000000,15.000000,7.000000,4.000000,2.000000,3.000000,3.000000,49.000000,5.000000,45.000000,9.000000,2.000000,2.000000,3.000000,25.000000,2.000000
75%,7500.25000,49.000000,4.000000,15679.500000,78.000000,22.000000,11.000000,7.000000,3.000000,4.000000,4.000000,75.000000,7.000000,52.000000,14.000000,4.000000,3.000000,3.000000,37.000000,4.000000
max,10000.00000,59.000000,5.000000,19999.000000,99.000000,29.000000,14.000000,9.000000,4.000000,5.000000,4.000000,99.000000,9.000000,59.000000,19.000000,4.000000,4.000000,4.000000,49.000000,4.000000

Detect Outliers

In [ ]:
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower) | (df[column] > upper)]

    print(column, len(outliers))

Employee_ID 0
Age 0
Job_Level 0
Monthly_Income 0
Hourly_Rate 0
Years_at_Company 0
Years_in_Current_Role 0
Years_Since_Last_Promotion 0
Work_Life_Balance 0
Job_Satisfaction 0
Performance_Rating 0
Training_Hours_Last_Year 0
Project_Count 0
Average_Hours_Worked_Per_Week 0
Absenteeism 0
Work_Environment_Satisfaction 0
Relationship_with_Manager 0
Job_Involvement 0
Distance_From_Home 0
Number_of_Companies_Worked 0

Remove Unnecessary Columns

In [ ]:
df = df.drop(columns=['Employee_ID'])

Final Dataset Information

In [ ]:
df.info()

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            10000 non-null  int64
 1   Gender                         10000 non-null  object
 2   Marital_Status                 10000 non-null  object
 3   Department                     10000 non-null  object
 4   Job_Role                       10000 non-null  object
 5   Job_Level                      10000 non-null  int64
 6   Monthly_Income                 10000 non-null  int64
 7   Hourly_Rate                    10000 non-null  int64
 8   Years_at_Company               10000 non-null  int64
 9   Years_in_Current_Role          10000 non-null  int64
 10  Years_Since_Last_Promotion     10000 non-null  int64
 11  Work_Life_Balance              10000 non-null  int64
 12  Job_Satisfaction               10000 non-null  int64
 13  Performance_Rating             10000 non-null  int64
 14  Training_Hours_Last_Year       10000 non-null  int64
 15  Overtime                       10000 non-null  object
 16  Project_Count                  10000 non-null  int64
 17  Average_Hours_Worked_Per_Week  10000 non-null  int64
 18  Absenteeism                    10000 non-null  int64
 19  Work_Environment_Satisfaction  10000 non-null  int64
 20  Relationship_with_Manager      10000 non-null  int64
 21  Job_Involvement                10000 non-null  int64
 22  Distance_From_Home             10000 non-null  int64
 23  Number_of_Companies_Worked     10000 non-null  int64
 24  Attrition                      10000 non-null  object
dtypes: int64(19), object(6)
memory usage: 1.9+ MB

,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,Years_in_Current_Role,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,58,Male,Single,Finance,Manager,5,7332,81,24,12,...,No,9,48,16,4,1,1,49,3,No
1,48,Female,Divorced,Hr,Assistant,4,6069,55,18,7,...,Yes,9,57,10,4,1,1,25,1,No
2,34,Female,Married,Marketing,Manager,4,11485,65,6,4,...,Yes,3,55,1,1,4,3,21,1,Yes
3,27,Female,Divorced,Hr,Manager,4,18707,28,12,9,...,No,9,53,2,3,4,1,46,2,No
4,40,Male,Married,Hr,Analyst,1,16398,92,3,9,...,No,1,54,11,1,1,1,43,4,No

Save Cleaned Dataset

In [ ]:
df.to_csv("cleaned_employee_attrition.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.